INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Mercedes', 5, 'RED', 1);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('BMW', 3, 'BLACK', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Audi', 5, 'WHITE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Volkswagen', 5, 'BLUE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Ferrari', 2, 'YELLOW', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Lamborghini', 2, 'GREEN', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Porsche', 2, 'ORANGE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Bugatti', 2, 'PURPLE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Aston Martin', 2, 'BROWN', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Jaguar', 5, 'PINK', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Lada', 5, 'GREY', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Mazda', 5, 'SILVER', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Lexus', 5, 'GOLD', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Ford', 5, 'BROWN', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Chevrolet', 4, 'BLACK', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Honda', 5, 'WHITE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Mitsubishi', 5, 'RED', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Nissan', 5, 'BLUE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Subaru', 5, 'GREEN', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Suzuki', 5, 'YELLOW', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Toyota', 5, 'ORANGE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Maserati', 2, 'PURPLE', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Lancia', 2, 'BROWN', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Citroen', 5, 'PINK', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Hyundai', 5, 'GREY', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Kia', 5, 'SILVER', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Peugeot', 5, 'GOLD', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Dacia', 5, 'BROWN', null);
INSERT INTO cars(brand, number_of_seats, color, person_id) VALUES('Skoda', 5, 'BLACK', null);


INSERT INTO people (first_name, last_name, company, type) VALUES ('John', 'Doe', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('William', 'Jones', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('David', 'Miller', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Richard', 'Davis', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Aby', 'Cyclette', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Paul', 'Ochon', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Jim', 'Nastique', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Ella', 'Lesyeubleu', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Lara', 'Pafromage', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Daisy', 'Draté', 'Acme', 1);
INSERT INTO people (first_name, last_name, company, type) VALUES ('Acme', null, 'Acme', 0);
